In [8]:
import numpy as np

In [9]:
def mineur(A,i,j,size):
    return np.concatenate(
        (np.concatenate((A[0:i,0:j],A[0:i,j+1:size]),axis=1) ,
        np.concatenate((A[i+1:size,0:j],A[i+1:size,j+1:size]),axis=1)),
        axis=0
    )

def det(A):
    #print(A.shape)
    if A.shape[0]==1:
        return A[0,0]
    if A.shape[0]==2:
        return A[0,0]*A[1,1]-A[0,1]*A[1,0]
    i=0
    dt=0.
    for j in range(A.shape[0]):
        dt+=np.power(-1,i+j)*A[i,j]*det(mineur(A,i,j,A.shape[0]))
    return dt


In [10]:
def test(A):
    res=np.linalg.det(A)
    print('With mumpy:',res)
    res=det(A)
    print('With my method:',res)
    

In [11]:
A=np.arange(1,5).reshape((2,2))
test(A)

With mumpy: -2.0000000000000004
With my method: -2


In [12]:
B=np.arange(1,10).reshape((3,3))
test(B)

With mumpy: 0.0
With my method: 0.0


In [13]:
C=np.array([2,-1,4,3,5,0,7,4,0]).reshape((3,3))
test(C)

With mumpy: -92.00000000000001
With my method: -92.0


In [14]:
D=np.arange(1,17).reshape((4,4))
test(D)

With mumpy: 0.0
With my method: 0.0


In [15]:
unif=np.random.randint(0,100,25)
print(unif)
E=unif.reshape((5,5))
print(E)
test(E)

[30 44 74 18 38 89 19 70 83 21 43 30 93 65 26 62 68 29 14 15 59 96 54 72
 63]
[[30 44 74 18 38]
 [89 19 70 83 21]
 [43 30 93 65 26]
 [62 68 29 14 15]
 [59 96 54 72 63]]
With mumpy: -559851054.0000013
With my method: -559851054.0


In [21]:
F=np.arange(1,101).reshape((10,10))
import time
start=time.time()
test(F) #cramer becomes late
end=time.time()
print('Duration:',end-start,'seconds')

With mumpy: -2.3389671972701e-111
With my method: 0.0
Duration: 15.757331132888794 seconds


In [17]:
G=np.arange(1,10001).reshape((100,100))
#test(G)   so so so late, please do not uncomment

#det(G) Cramer, so so so late
np.linalg.det(G)

0.0

In [18]:
G=np.arange(1,1000001).reshape((1000,1000))
np.linalg.det(G)

0.0

In [22]:
def substitute_column(A,B,col):
    res=A.copy()
    res[:,col:col+1]=B.copy()
    return res
    
def cramer(A,B):
    x=np.zeros((A.shape[0],1))
    mat=0
    d=det(A)
    for j in range(A.shape[0]):
        mat=substitute_column(A,B,j)
        x[j]=det(mat)/d
    return x
A=np.array([2,5,3,1,4,2,7,1,-2]).reshape((3,3))
B=np.array([[-1],[-3],[-4]])
cramer(A,B)

array([[ 1.],
       [-3.],
       [ 4.]])