In [37]:
import numpy as np

        
def solve_triangular(A,B):
    A=A.astype(float).copy()
    B=B.astype(float).copy()
    n=A.shape[0]
    X=np.zeros((n,1))
    X[n-1]=B[n-1]/A[n-1,n-1]
    for i in range(n-2,-1,-1):
        S=0
        for j in range(i,n):
            S+=A[i,j]*X[j]
        X[i]=(B[i]-S)/A[i,i]
    return X

def gauss(A,B):
    n=A.shape[0]
    X=np.zeros((n,1))
    Aprime=A.copy()
    Bprime=B.copy()
    
    for k in range(n-1):
        for j in range(k+1,n):
            pivot=Aprime[k,k]
            
            if pivot==0:
                
            
                max_index=np.argmax(np.abs(Aprime[j:n,k]))
                real_max_index=max_index+j
                
                Aprime[k],Aprime[real_max_index]=Aprime[real_max_index].copy(),Aprime[k].copy()
                Bprime[k],Bprime[real_max_index]=Bprime[real_max_index].copy(),Bprime[k].copy()
                pivot=Aprime[k,k]
        
                #print(Bprime)
            print([j,k])
            alpha=Aprime[j,k]/pivot
            print(alpha)
        
            Aprime[j]=Aprime[j]-alpha*Aprime[k]
        
            Bprime[j]=Bprime[j]-alpha*Bprime[k]
            print(Aprime)
            print(Bprime)
            
    #print(Aprime)
    #print(Bprime)
            
    return solve_triangular(Aprime,Bprime)

In [24]:
A=np.array([1,-1,1,2,-1,3,3,-2,2]).reshape((3,3))
B=np.array([[4],[5],[1]])
X=gauss(A,B)
print(X)
A@X

2.0
[[ 4]
 [-3]
 [ 1]]
3.0
[[  4]
 [ -3]
 [-11]]
1.0
[[ 4]
 [-3]
 [-8]]
[[-7.]
 [-7.]
 [ 4.]]


array([[4.],
       [5.],
       [1.]])

In [25]:
A=np.array([
            2,2,-1,
            1,4,-1,
            3,2,1]
    ,dtype=float
).reshape((3,3))

B=np.array([[-5],[-10],[2]]
           ,dtype=float
          )
X=gauss(A,B)

print(X)
A@X

0.5
[[-5. ]
 [-7.5]
 [ 2. ]]
1.5
[[-5. ]
 [-7.5]
 [ 9.5]]
-0.3333333333333333
[[-5. ]
 [-7.5]
 [ 7. ]]
[[ 1.]
 [-2.]
 [ 3.]]


array([[ -5.],
       [-10.],
       [  2.]])

In [30]:
A=np.array([2,1,2,-3,3,-2,1,-1,1,1,-1,-1,1,-1,3,-1],dtype=float).reshape((4,4))
B=np.array([[18],[12],[1],[15]],dtype=float)
X=gauss(A,B)
print(X)
A@X

1.5
[[ 2.   1.   2.  -3. ]
 [ 0.  -3.5 -2.   3.5]
 [ 1.   1.  -1.  -1. ]
 [ 1.  -1.   3.  -1. ]]
[[ 18.]
 [-15.]
 [  1.]
 [ 15.]]
0.5
[[ 2.   1.   2.  -3. ]
 [ 0.  -3.5 -2.   3.5]
 [ 0.   0.5 -2.   0.5]
 [ 1.  -1.   3.  -1. ]]
[[ 18.]
 [-15.]
 [ -8.]
 [ 15.]]
0.5
[[ 2.   1.   2.  -3. ]
 [ 0.  -3.5 -2.   3.5]
 [ 0.   0.5 -2.   0.5]
 [ 0.  -1.5  2.   0.5]]
[[ 18.]
 [-15.]
 [ -8.]
 [  6.]]
-0.14285714285714285
[[ 2.          1.          2.         -3.        ]
 [ 0.         -3.5        -2.          3.5       ]
 [ 0.          0.         -2.28571429  1.        ]
 [ 0.         -1.5         2.          0.5       ]]
[[ 18.        ]
 [-15.        ]
 [-10.14285714]
 [  6.        ]]
0.42857142857142855
[[ 2.          1.          2.         -3.        ]
 [ 0.         -3.5        -2.          3.5       ]
 [ 0.          0.         -2.28571429  1.        ]
 [ 0.          0.          2.85714286 -1.        ]]
[[ 18.        ]
 [-15.        ]
 [-10.14285714]
 [ 12.42857143]]
-1.25
[[ 2.00000000e+00  1.00

array([[18.],
       [12.],
       [ 1.],
       [15.]])

In [38]:
A=np.array([
            0,1,3,
            5,2,3,
            6,8,1]
    ,dtype=float
).reshape((3,3))

B=np.array([[1],[4],[1]]
           ,dtype=float
          )
X=gauss(A,B)

#print(X)
#A@X

[1, 0]
0.8333333333333334
[[ 6.          8.          1.        ]
 [ 0.         -4.66666667  2.16666667]
 [ 0.          1.          3.        ]]
[[1.        ]
 [3.16666667]
 [1.        ]]
[2, 0]
0.0
[[ 6.          8.          1.        ]
 [ 0.         -4.66666667  2.16666667]
 [ 0.          1.          3.        ]]
[[1.        ]
 [3.16666667]
 [1.        ]]
[2, 1]
-0.21428571428571427
[[ 6.          8.          1.        ]
 [ 0.         -4.66666667  2.16666667]
 [ 0.          0.          3.46428571]]
[[1.        ]
 [3.16666667]
 [1.67857143]]
