In [260]:
import numpy as np

In [261]:
zeros33=np.zeros((3,3))
is_diag(zeros33)

True

In [262]:
ones33=np.ones((3,3))
is_diag(ones33)

False

In [301]:
I=np.identity(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [303]:
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [304]:
I=np.eye(3,dtype=int)
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [306]:
I=np.identity(3,dtype=str)
I

array([['1', '', ''],
       ['', '1', ''],
       ['', '', '1']], dtype='<U1')

In [307]:
def is_diag(mat):
    for i in range(mat.shape[0]):
        for j in range(mat.shape[0]):
            if i!=j and mat[i,j]!=0:
                return False
    return True       



In [308]:
def is_upper_triangular(mat):
    for i in range(mat.shape[0]):
        for j in range(0,i):
            if mat[i,j]!=0:
                return False
    return True 

def is_lower_triangular(mat):
    for i in range(mat.shape[0]):
        for j in range(i-1,mat.shape[0]):
            if mat[i,j]!=0:
                return False
    return True 

In [265]:
mat=np.array([3,1,4,0,2,6,0,0,8]).reshape((3,3))
is_upper_triangular(mat)

True

In [266]:
is_lower_triangular(mat)

False

In [267]:
is_lower_triangular(zeros33)

True

In [268]:
is_upper_triangular(ones33)

False

In [269]:
def is_triangular(mat):
    return is_upper_triangular(mat) or s_lower_triangular(mat)

In [270]:
def is_tridiagonal(mat):
    for i in range(mat.shape[0]):
        for j in range(0,mat.shape[0]):
            if j!=i and j!=i-1 and j!=i+1 and mat[i,j]!=0:
                return False
    return True

In [271]:
is_tridiagonal(zeros33)

True

In [272]:
is_tridiagonal(ones33)

False

In [273]:
print(mat)
print(np.transpose(mat))
mat.T#another way


%prun for i in range(1000000):np.transpose(mat)
#%prun for i in range(1000000):mat.T#faster

[[3 1 4]
 [0 2 6]
 [0 0 8]]
[[3 0 0]
 [1 2 0]
 [4 6 8]]
 

In [311]:
def is_symetric(mat):
    return np.array_equal(mat,mat.T)
print(is_symetric(mat))
print(is_symetric(I))

False
True


In [274]:
np.linalg.det(ones33)

0.0

In [275]:
help(np.linalg.det)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

det(a)
    Compute the determinant of an array.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Input array to compute determinants for.
    
    Returns
    -------
    det : (...) array_like
        Determinant of `a`.
    
    See Also
    --------
    slogdet : Another way to represent the determinant, more suitable
      for large matrices where underflow/overflow may occur.
    scipy.linalg.det : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    The determinant is computed via LU factorization using the LAPACK
    routine ``z/dgetrf``.
    
    Examples
    --------
    The determinant of a 2-D array [[a, b], [c, d]] is ad - bc:
    
    >>> a = np.array([[1, 2], [3, 4]])
    >>> np.linalg.det(a)
    -2.0 # may vary
    
    Computing determinants for a stack of matr

In [276]:
np.linalg.inv(ones33) #not inversible(singular matrix)

LinAlgError: Singular matrix

In [319]:
K=np.array([3,-1,2,1,0,4,-2,3,1,0,7,1,0,2,0,4]).reshape((4,4))
print(K)
np.linalg.det(K)

[[ 3 -1  2  1]
 [ 0  4 -2  3]
 [ 1  0  7  1]
 [ 0  2  0  4]]


190.0

In [324]:
K=np.array([2,5,3,1,4,2,7,1,-2]).reshape((3,3))
print(K)
np.linalg.det(K)

[[ 2  5  3]
 [ 1  4  2]
 [ 7  1 -2]]


-20.99999999999999

In [ ]:
K=np.array([2,-1,4,3,5,0,7,4,0]).reshape((3,3))
print(K)
np.linalg.det(K)

In [ ]:
def is_regular(mat):
    return np.linalg.det(mat)!=0
print(is_regular(ones33))
print(is_regular(mat))
print(np.linalg.det(mat))


In [ ]:
A=np.array([1,2,5,9,7,0,-4,2,1]).reshape((3,3))
np.linalg.inv(A)

In [ ]:
help(np.linalg.solve)

In [ ]:
A=np.array([4,-6,8,2,-6,10,-15,-3,8,-15,26,-1,2,-3,-1,62]).reshape((4,4))
B=np.array([-6,6,-1,-13]).reshape((4,1))
print(A)
print(B)
X=np.linalg.solve(A,B)
print(X)

In [ ]:
np.allclose(np.dot(A, X), B)

In [ ]:
np.dot(A, X)

In [ ]:
np.trace(A)

In [ ]:
X=np.ones((3,3))+np.full((3,3),5.5)-A[1:4,1:4]#addition multiplication
print(X)
2*X

In [ ]:
8+X-3#X+5

In [ ]:
X//2

In [ ]:
X%2

In [ ]:
X**4

In [ ]:
np.power(X,4)

In [ ]:
%prun [X**4 for i in range(1000000)]

In [ ]:
%prun [np.power(X,4) for i in range(1000000)]#faster

In [ ]:
#X**0.3 #error
#np.power(X,0.3)#error

In [ ]:
5/X

In [ ]:
5//X

In [ ]:
X**-9

In [ ]:
np.power(X,-9)

In [ ]:
A=np.arange(5)
A

In [ ]:
B=np.array([[5,6,9,8,7]])
B

In [ ]:
A*B

In [ ]:
A/B

In [ ]:
A//B

In [ ]:
A%B

In [ ]:
A**B

In [ ]:
np.power(A,B)

In [ ]:
A=np.array([[5,5,8,-3,6,4,9,3,0]]).reshape(3,3)
A

In [ ]:
B=np.array([[1,4,8,-8,-6,2,9,2,0]]).reshape(3,3)
B

In [ ]:
A*B #item by item product

In [ ]:
np.dot(A,B)#matrix product

In [ ]:
print(A)
np.sqrt(np.abs(A))

In [ ]:
np.exp(A)

In [ ]:
print(A)
print(B)
print(np.dot(A,B))#dot product A and B
print(A@B)#The fastest way to dot product two matrixes
print(np.matmul(A,B))#implements the @ operator


In [ ]:
C=np.full((3,3),2)
D=np.arange(1,10).reshape(3,3)
print(A) 
print(B) 
print(C)
print(D)
print((A@B)@(C@D))
print(A@B@C@D)

np.linalg.multi_dot([A,B,C,D])

In [ ]:
U=np.arange(1,6).reshape(5,1)
V=np.array([[4,-2,3]])
print(U.shape)
print(V.shape)
print(U)
print(V)
print(U@V)


In [ ]:
U=np.arange(1,6).reshape(1,5)
V=np.array([[4,-2,3,-2,6]])
print(U.shape)
print(V.shape)
print(U)
print(V)
np.vdot(U,V)

U=np.arange(1,6)
V=np.array([[4,-2,3,-2,6]])
np.vdot(U,V)#the doct product of the 2 vectors(their scalor product)


In [ ]:
A=np.arange(1,17).reshape(4,4)
B=np.arange(-17,-1).reshape(4,4)

np.inner
np.outer
np.tensordot
np.kron

In [278]:
np.linalg.matrix_power(A,3)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
res=np.linalg.qr(A)
print(res)
print(type(res))
print(len(res))
for i in res :
    print (i)
Q,R=res
print(Q)
print(R)
print(Q@R)

In [284]:
from scipy.linalg import lu
res=lu(A)
print(res)
print(type(res))
print(len(res))
for i in res :
    print (i)
P,Q,R=res
print(Q)
print(R)
print(P@Q@R)

(array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]]), array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.07692308,  1.        ,  0.        ,  0.        ],
       [ 0.69230769,  0.33333333,  1.        ,  0.        ],
       [ 0.38461538,  0.66666667, -0.5       ,  1.        ]]), array([[ 1.30000000e+01,  1.40000000e+01,  1.50000000e+01,
         1.60000000e+01],
       [ 0.00000000e+00,  9.23076923e-01,  1.84615385e+00,
         2.76923077e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.77635684e-15,
        -1.77635684e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]]))
<class 'tuple'>
3
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.07692308  1.          0.          0.        ]
 [ 0.69230769  0.33333333  1.          0.        ]
 [ 0.38461538  0.66666667 -0.5         1.        ]]
[[ 1.30000000e+01  1.4000

In [286]:
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [293]:
A = np.array([[10, 1, 2],
              [1, 11, 3],
              [2, 3, 12]])
C=np.linalg.cholesky(A)
C@C.T

array([[10.,  1.,  2.],
       [ 1., 11.,  3.],
       [ 2.,  3., 12.]])

In [297]:
SVD=np.linalg.svd(A)
print(len(SVD))
print(SVD)

3
SVDResult(U=array([[-0.37435872,  0.81558342, -0.4412247 ],
       [-0.57735027, -0.57735027, -0.57735027],
       [-0.7256185 ,  0.03860509,  0.68701342]]), S=array([15.41883268,  9.38677016,  8.19439717]), Vh=array([[-0.37435872, -0.57735027, -0.7256185 ],
       [ 0.81558342, -0.57735027,  0.03860509],
       [-0.4412247 , -0.57735027,  0.68701342]]))
